### ISSUE TITLE
Add example nr 2

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/derp#10]

**Comment by ReinhardSchmidt** [comment]
please add example 2
gif: https://drive.google.com/open?id=1N-41E4lUVM1PZrP-GoUuL7PdjhLSuBdK&authuser=zrh%40hoprnet.org&usp=drive_fs
button-text: Example 2: NFT Frontrun button
headline: NFT Frontrun button
copy: When you bid on an NFT in a marketplace, your wallet will send a request to estimate the necessary gas price. As part of this request, the RPC endpoint will learn your IP address, your wallet address, the precise NFT you intend to buy and the amount of your bid. All this happens before the transaction is confirmed, giving a malicious actor all the information they need to frontrun you by placing a higher bid or setting a higher gas price. In an NFT minting event, this could mean the difference between getting an NFT or missing out.

DERP doesn’t work with all NFT marketplaces: OpenSea, for example, uses a private RPC provider which we can’t duplicate the functionality of. But that’s not necessarily better! With crypto, you shouldn’t have to trust black box service providers with your data.

––––

please also do add example 3:
gif: https://drive.google.com/file/d/1Mra12UAx_qKkPsVWsckTkwC5BT0YdNwz/view?usp=sharing
button-text: Example 3: DEX MEV 
headline: DEX MEV 
copy: When you use a DEX like Uniswap, many RPC requests are needed to populate the UI with data about your balances, the token pair you want to swap and details like price and slippage.

All this information is sent to the RPC provider before your transaction is broadcast. A malicious provider can use this information to perform a sandwich attack on your transaction, maxing out the slippage and effectively taking money from you.

Separately, DEX RPC endpoints also expose a large amount of identifying metadata. Simply browsing swaps reveals information about your portfolio, even if you never make a transaction. Combined with your IP address, which is also leaked, this can facilitate precise identification of you and your crypto holdings.

**Comment by tolbrino** [comment]
Content added.
