### ISSUE TITLE
find out why Frame shows nothing on DERP

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/derp#32]
## Expected Behavior
When adding the DERP endpoint for some chain to Frame and start using Frame, I expect to see at least some requests on the DERP website

## Current Behavior
DERP website shows nothing

## (Optional) Possible Solution
I checked that Frame does indeed respect user-specified RPCs. E.g. when adding a bogus URL, it shows that the network is disconnected. It's unclear why DERP shows nothing in this case but would be useful to find out in order to keep the conversation going with Frame.

**Comment by mjadach-iv** [comment]
New version works fine
