### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/derp#7]
1. Please stack the gif above the text -> implement a function that switches from a two-column grid to one-column-approach:
![Bildschirmfoto 2022-01-17 um 12 52 47](https://user-images.githubusercontent.com/78225531/149764977-51e5d7bd-b617-414f-aa79-2ae0a3ade543.png)

2. Improve the readability of the table by shrinking the typesize, but also removing all collisions, for ex. "Network DERP-EHT:
![Bildschirmfoto 2022-01-17 um 12 46 29](https://user-images.githubusercontent.com/78225531/149765268-1a92aa5b-ad9e-473c-a81d-336c52774d3f.png)

**Comment by tolbrino** [comment]
Now using a single-column layout on smaller screens.
