### ISSUE TITLE
CSS-formatting: smaller details

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/derp#9]
- Link look: underlined, coloured in #0000b4
![Bildschirmfoto 2022-01-20 um 12 31 12](https://user-images.githubusercontent.com/78225531/150330941-026483f5-2141-4e67-95fb-8dc0908279ec.png)

- Can you use the Medium-cut (currently Regular) of Source Code Pro in CAPITAL letters for the following three subheadlines: 
"I THOPUGHT WEB3 WAS PRIVATE?", "SETUP", "METAMASK"
for. Ex. here:
![Bildschirmfoto 2022-01-20 um 12 55 40](https://user-images.githubusercontent.com/78225531/150334315-9a90377f-eab1-4d97-82c2-d4f3ac3d8ecd.png)

- Add the HOPR-favicon as icon, 100% available :) : 
128px: https://drive.google.com/file/d/1mCVTlchilIHO_Oyx4-4TBruYItNQaZF3/view?usp=sharing
32px: https://drive.google.com/file/d/1UE1nSPQLJlxuEH90wFRbsBNjSOLHTuOv/view?usp=sharing
Or just grab the one used on hoprnet.org

- Rename the button "EXAMPLE 1" into "EXAMPLE 1: METAMASK LINKABILITY"

- Inside EXAMPLE 1, rename the Headline "METAMASK LINKABILITY"

- And if you still got time, some smaller white space between the "accordeon" and your leaderboard. Preferably the same value as the one between intro and the example-buttons.

**Comment by tolbrino** [comment]
Everything implemented except for the spacing.
